/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface CertificateVerificationInterface extends Interface {
    getFunction(nameOrSignature: "getCertificateHash" | "issueCertificate" | "owner" | "revokeCertificate" | "totalCertificates" | "verifyCertificate"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CertificateIssued" | "CertificateRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'getCertificateHash', values: [string]): string;
encodeFunctionData(functionFragment: 'issueCertificate', values: [string, string, string, string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeCertificate', values: [string]): string;
encodeFunctionData(functionFragment: 'totalCertificates', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyCertificate', values: [string]): string;

    decodeFunctionResult(functionFragment: 'getCertificateHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issueCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeCertificate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalCertificates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyCertificate', data: BytesLike): Result;
  }

  
    export namespace CertificateIssuedEvent {
      export type InputTuple = [studentId: string, studentName: string, courseName: string, grade: string, issueDate: BigNumberish];
      export type OutputTuple = [studentId: string, studentName: string, courseName: string, grade: string, issueDate: bigint];
      export interface OutputObject {studentId: string, studentName: string, courseName: string, grade: string, issueDate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CertificateRevokedEvent {
      export type InputTuple = [studentId: string, revokeDate: BigNumberish];
      export type OutputTuple = [studentId: string, revokeDate: bigint];
      export interface OutputObject {studentId: string, revokeDate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface CertificateVerification extends BaseContract {
    
    connect(runner?: ContractRunner | null): CertificateVerification;
    waitForDeployment(): Promise<this>;

    interface: CertificateVerificationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getCertificateHash: TypedContractMethod<
      [_studentId: string, ],
      [string],
      'view'
    >
    

    
    issueCertificate: TypedContractMethod<
      [_studentId: string, _studentName: string, _courseName: string, _grade: string, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    revokeCertificate: TypedContractMethod<
      [_studentId: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalCertificates: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    verifyCertificate: TypedContractMethod<
      [_studentId: string, ],
      [[string, string, string, bigint, boolean] & {studentName: string, courseName: string, grade: string, issueDate: bigint, isRevoked: boolean }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getCertificateHash'): TypedContractMethod<
      [_studentId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'issueCertificate'): TypedContractMethod<
      [_studentId: string, _studentName: string, _courseName: string, _grade: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'revokeCertificate'): TypedContractMethod<
      [_studentId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalCertificates'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifyCertificate'): TypedContractMethod<
      [_studentId: string, ],
      [[string, string, string, bigint, boolean] & {studentName: string, courseName: string, grade: string, issueDate: bigint, isRevoked: boolean }],
      'view'
    >;

    getEvent(key: 'CertificateIssued'): TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
getEvent(key: 'CertificateRevoked'): TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;

    filters: {
      
      'CertificateIssued(string,string,string,string,uint256)': TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
      CertificateIssued: TypedContractEvent<CertificateIssuedEvent.InputTuple, CertificateIssuedEvent.OutputTuple, CertificateIssuedEvent.OutputObject>;
    

      'CertificateRevoked(string,uint256)': TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
      CertificateRevoked: TypedContractEvent<CertificateRevokedEvent.InputTuple, CertificateRevokedEvent.OutputTuple, CertificateRevokedEvent.OutputObject>;
    
    };
  }